# Generated by Django 4.2.5 on 2023-09-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
    ]
