# Generated by Django 4.2.5 on 2023-09-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(default='kg', max_length=2),
            preserve_default=False,
        ),
    ]
