# Generated by Django 4.2.5 on 2023-09-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=199),
            preserve_default=False,
        ),
    ]
