# Generated by Django 4.2.5 on 2023-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_original_price_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='original_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
    ]
