# Generated by Django 4.2.5 on 2023-09-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='almad', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
