# Generated by Django 4.2.5 on 2023-09-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(default=None, upload_to='images/products/'),
        ),
    ]
