# Generated by Django 4.2.5 on 2023-10-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='order',
            field=models.ForeignKey(default=214, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
            preserve_default=False,
        ),
    ]
