# Generated by Django 4.2.5 on 2023-10-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_returnorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=20)),
                ('coupon_code', models.CharField(max_length=20)),
                ('min_purchase', models.FloatField()),
                ('coupon_discount', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
