# Generated by Django 4.2.5 on 2023-09-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='images/category'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='as', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_category',
            name='slug',
            field=models.SlugField(default='dfs', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
