# Generated by Django 4.2.5 on 2023-09-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variant'),
        ('carts', '0003_alter_cartitem_product'),
    ]

    operations = [
    ]
