# Generated by Django 4.2.5 on 2023-09-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_slug'),
        ('carts', '0004_merge_20230927_1256'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
        ),


    ]
