# Generated by Django 4.2.5 on 2023-09-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_slug'),
        ('carts', '0006_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
            preserve_default=False,
        ),
    ]
