# Generated by Django 4.2.5 on 2023-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='9989776677', max_length=15),
            preserve_default=False,
        ),
    ]
