# Generated by Django 4.2.5 on 2023-09-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='nandu@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
