# Generated by Django 4.2.5 on 2023-10-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_images'),
        ('carts', '0011_cartitem_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ManyToManyField(blank=True, to='product.productvariant'),
        ),
    ]
