# Generated by Django 4.2.5 on 2023-10-02 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_images'),
        ('carts', '0012_remove_cartitem_variant_cartitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, default=31, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
            preserve_default=False,
        ),
    ]
